server:
  port: 8084

spring:
  application:
    name: api-gateway
  cloud:
    config:
      enabled: false
    import-check:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # Auth service routes - PUBLIC endpoints first
        - id: auth-service-internal
          uri: lb://auth-service
          predicates:
            - Path=/internal/**
          filters:
            - RewritePath=/internal/(?<path>.*), /internal/$\{path}

        # Auth service - public auth endpoints
        - id: auth-service-public
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**

        # Auth service - protected user endpoints
        - id: auth-service-users
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/users/**

        # Account service routes
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/api/v1/accounts/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

