server:
  port: 8081

spring:
  config:
    import:
      - "optional:configserver:"
      - "optional:classpath:keys.properties"
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: lewis
    password: gakpo901
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

security:
  jwt:
    token:
      secret-key: bmWJ5JO4lrwV/FkyErvimp1UmKIQgbEIat+eFWARwTo=

api:
  prefix: /api/v1

management:
  endpoints:
    web:
      exposure:
        include: health,info