server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    config:
      enabled: false
    import-check:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # Internal service routes - HIGHEST PRIORITY
        - id: auth-service-internal
          uri: lb://auth-service
          predicates:
            - Path=/internal/users/**
          filters:
            - RewritePath=/internal/users/(?<path>.*), /internal/users/$\{path}

        - id: account-service-internal
          uri: lb://account-service
          predicates:
            - Path=/internal/accounts/**
          filters:
            - RewritePath=/internal/accounts/(?<path>.*), /internal/accounts/$\{path}

        - id: transaction-service-internal
          uri: lb://transaction-service
          predicates:
            - Path=/internal/transactions/**
          filters:
            - RewritePath=/internal/transactions/(?<path>.*), /internal/transactions/$\{path}

        # Auth service - public auth endpoints
        - id: auth-service-public
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**

        # Auth service - protected user endpoints
        - id: auth-service-users
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/users/**

        # Account service routes
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/api/v1/accounts/**

        # Transaction service routes
        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/api/v1/transactions/**

        # Notification service routes
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/v1/notifications/**

        # Customer Analytics service routes - UPDATED
        - id: customer-analytics-service
          uri: lb://customer-analytics-service
          predicates:
            - Path=/api/v1/behavior/**
          filters:
            - RewritePath=/api/v1/behavior/(?<path>.*), /api/v1/behavior/$\{path}

        - id: customer-analytics-recommendations
          uri: lb://customer-analytics-service
          predicates:
            - Path=/api/v1/recommendations/**
          filters:
            - RewritePath=/api/v1/recommendations/(?<path>.*), /api/v1/recommendations/$\{path}

        - id: customer-analytics-patterns
          uri: lb://customer-analytics-service
          predicates:
            - Path=/api/v1/patterns/**
          filters:
            - RewritePath=/api/v1/patterns/(?<path>.*), /api/v1/patterns/$\{path}

        - id: customer-analytics-summary
          uri: lb://customer-analytics-service
          predicates:
            - Path=/api/v1/analytics/**
          filters:
            - RewritePath=/api/v1/analytics/(?<path>.*), /api/v1/analytics/$\{path}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

# Application configuration
api:
  prefix: /api/v1

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG