server:
  port: 8085

spring:
  application:
    name: notification-service
  config:
    import: "optional:classpath:keys.properties"
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  cloud:
    config:
      enabled: false
    import-check:
      enabled: false
  security:
    jwt:
      token:
        secret-key: ${secret.key}
  mail:
    host: ${mail.host}
    port: ${mail.port}
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
        loggerLevel: full
      auth-service:
        connectTimeout: 10000
        readTimeout: 10000

api:
  prefix: /api/v1

management:
  endpoints:
    web:
      exposure:
        include: health,info
